FROM node:20-alpine

WORKDIR /app/frontend
ENV VITE_WS_URL=${VITE_WS_URL:-ws://localhost:8000/ws}

COPY frontend/package*.json ./
RUN npm install

COPY frontend/ .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]
